"""Reusable response formatters for DBQA output.

These are display-layer helpers that convert raw XML record dicts into
clean, human-readable display dicts.  They do **not** query the XMLStore.

Public API::

    format_user(user)              → display dict
    format_return(ret)             → display dict
    format_instance(inst)          → display dict
    format_table(records, cols)    → list of display dicts
    format_not_found(...)          → standard not-found response dict
    format_count_summary(...)      → concise summary string
"""
from __future__ import annotations

from typing import Any

# ── Sensitive field guard ─────────────────────────────────────────────────────
# These are stripped from all output — mirrors XMLStore._SENSITIVE_FIELDS
_SENSITIVE: frozenset[str] = frozenset({
    "Password", "SecondPassword", "ThirdPassword",
    "FourthPassword", "FifthPassword", "Answer",
})

# ── Field display configurations ─────────────────────────────────────────────
# Each entry is (xml_field_key, display_label).  Only present fields are shown.

_USER_FIELDS: list[tuple[str, str]] = [
    ("Name",              "Name"),
    ("LoginId",           "Login ID"),
    ("EmailId",           "Email"),
    ("MobileNumber",      "Mobile"),
    ("DeptName",          "Department"),
    ("RoleName",          "Role"),
    ("Status",            "Status"),
    ("LastLoginDT",       "Last Login"),
    # No "Failed Logins" column: an operational security counter is not part
    # of a user's identity and does not belong in a general user listing.
    # Questions that ask about it specifically are answered from
    # FailedLoginCount directly — see agent/db_qa_router._CONDITIONAL_FIELDS,
    # which is what the live table-rendering path actually consults.
    ("UserCreationDate",  "Created On"),
]

_RETURN_FIELDS: list[tuple[str, str]] = [
    ("Name",        "Return Name"),
    ("ReturnId",    "Return ID"),
    ("PeriodName",  "Frequency"),
    ("Description", "Description"),
    ("Status",      "Status"),
]

_INSTANCE_FIELDS: list[tuple[str, str]] = [
    ("ReturnName",    "Report"),
    ("ReportingDate", "Reporting Date"),
    ("DTC",           "Generated On"),
    ("UserName",      "Generated By"),
    ("StatusLabel",   "Status"),
]

_DEPT_FIELDS: list[tuple[str, str]] = [
    ("Name",              "Department"),
    ("DeptId",            "Dept ID"),
    ("UserCount",         "Users"),
    ("TotalReturnCount",  "Returns"),
    ("XBRLReturnCount",   "XBRL Returns"),
    ("NonXBRLReturnCount","Non-XBRL Returns"),
]

_ROLE_FIELDS: list[tuple[str, str]] = [
    ("Name",        "Role"),
    ("RoleId",      "Role ID"),
    ("Description", "Description"),
    ("Status",      "Status"),
]


# ── Value normalisation ───────────────────────────────────────────────────────

def _display(v: Any) -> str:
    """Convert a raw XML attribute value to a clean display string."""
    if v is None or str(v).strip() == "":
        return "—"
    s = str(v).strip()
    if s.lower() == "true":
        return "Active"
    if s.lower() == "false":
        return "Inactive"
    return s


# ── Public formatters ─────────────────────────────────────────────────────────

def format_user(user: dict) -> dict:
    """Display-ready dict for a single user record.

    Strips sensitive fields; translates Status booleans to Active/Inactive.
    """
    return {
        label: _display(user.get(key))
        for key, label in _USER_FIELDS
        if key not in _SENSITIVE and key in user
    }


def format_return(ret: dict) -> dict:
    """Display-ready dict for a single return / report record."""
    return {
        label: _display(ret.get(key))
        for key, label in _RETURN_FIELDS
        if key in ret
    }


def format_instance(inst: dict) -> dict:
    """Display-ready dict for a single instance-log / submission record."""
    return {
        label: _display(inst.get(key))
        for key, label in _INSTANCE_FIELDS
        if key in inst
    }


def format_dept(dept: dict) -> dict:
    """Display-ready dict for a single department record."""
    return {
        label: _display(dept.get(key))
        for key, label in _DEPT_FIELDS
        if key in dept
    }


def format_role(role: dict) -> dict:
    """Display-ready dict for a single role record."""
    return {
        label: _display(role.get(key))
        for key, label in _ROLE_FIELDS
        if key in role
    }


def format_table(records: list[dict], cols: list[tuple[str, str]]) -> list[dict]:
    """Generic table formatter.

    Args:
        records: Raw data dicts (XML attributes).
        cols:    ``[(field_key, display_label), ...]`` pairs to include.

    Returns:
        List of display dicts keyed by *display_label*, omitting sensitive keys.
    """
    return [
        {label: _display(r.get(key)) for key, label in cols if key not in _SENSITIVE}
        for r in records
    ]


def format_count_summary(total: int, active: int, inactive: int, entity: str = "users") -> str:
    """One-line count summary string."""
    return f"Total {entity}: **{total}** ({active} active, {inactive} inactive)"


def format_not_found(
    entity_type: str,
    query: str,
    *,
    suggestions: list[str] | None = None,
) -> dict:
    """Build a standardised not-found response with optional "Did you mean…?" suggestions."""
    msg = f"No {entity_type} found matching '{query}'."
    if suggestions:
        opts = ", ".join(f'"{s}"' for s in suggestions[:3])
        msg += f" Did you mean: {opts}?"
    return {
        "found": False,
        "records": [],
        "summary": msg,
        "meta": {"suggestions": suggestions or []},
    }
