"""Response templates for the new-taxonomy db_qa intents.

One template string per Intent, populated ONLY from a handler's result dict
(summary/meta/records) — no intent's factual content is ever generated by
an LLM here. beautifier.py (Ollama) remains available as an OPTIONAL
enhancement layer applied on top of the rendered template string, not a
replacement for it — if beautification is disabled or fails, the caller
already has a good, fact-only response from render().

render() never raises: a missing template or a missing meta key falls back
to result["summary"], which every handler always populates.
"""
from __future__ import annotations

from backend.db_qa.intents.taxonomy import Intent

# Fields that hold ciphertext under 6.0 (see versions/v6_0_schema.py —
# users.Name/EmailId/MobileNumber map onto 6.0's encrypted FirstName/
# EmailId/PhoneNumber attributes). Masked at render time so a template
# never surfaces an undecryptable blob to the end user.
_POSSIBLY_ENCRYPTED_USER_FIELDS = frozenset({"Name", "EmailId", "MobileNumber"})
_ENCRYPTED_PLACEHOLDER = "(stored encrypted — not displayable)"


def _looks_like_ciphertext(value: str) -> bool:
    """Heuristic only — 6.0's encrypted fields are base64-ish blobs with no
    spaces and often padding characters; this is intentionally conservative
    (better to occasionally under-mask than to mask a legitimate short value
    like an email address, which templates handle via the field allowlist
    below instead of this heuristic alone)."""
    if not value or " " in value or "@" in value:
        return False
    return len(value) >= 16 and (value.endswith("=") or value.endswith("=="))


def _display_value(field: str, value) -> str:
    if isinstance(value, str) and field in _POSSIBLY_ENCRYPTED_USER_FIELDS and _looks_like_ciphertext(value):
        return _ENCRYPTED_PLACEHOLDER
    return value


TEMPLATES: dict[Intent, str] = {
    Intent.USER_PROFILE: "{summary}",
    Intent.USER_FIELD: "{summary}",
    Intent.USER_LIST: "{summary}",
    Intent.USERS_BY_DEPARTMENT: "{summary}",
    Intent.USERS_BY_ROLE: "{summary}",
    Intent.USERS_WITH_ROLES_AND_DEPARTMENTS: "{summary}",

    Intent.DEPARTMENT_LIST: "{summary}",
    Intent.DEPARTMENT_PROFILE: "{summary}",
    Intent.DEPARTMENT_RETURNS: "{summary}",
    Intent.DEPARTMENTS_WITH_RETURN_ACCESS: "{summary}",
    Intent.DEPARTMENT_HAS_RETURN: "{summary}",

    Intent.ROLE_LIST: "{summary}",
    Intent.ROLE_PROFILE: "{summary}",
    Intent.ROLE_USERS: "{summary}",
    Intent.ROLE_PEER_COUNT: "{summary}",

    Intent.PERMISSION_PROFILE: "{summary}",
    Intent.PERMISSION_CHECK: "{summary}",
    Intent.ROLES_WITH_PERMISSION: "{summary}",
    Intent.ROLE_MODULE_ACCESS: "{summary}",
    Intent.ROLE_PERMISSION_DIFF: "{summary}",

    Intent.USER_LEVEL_LIST: "{summary}",
    Intent.USER_LEVEL_SELF: "{summary}",

    Intent.PERIOD_LIST: "{summary}",
    Intent.PERIOD_LOOKUP: "{summary}",
    Intent.RETURNS_BY_FREQUENCY: "{summary}",

    Intent.RETURN_LIST: "{summary}",
    Intent.RETURN_PROFILE: "{summary}",
    Intent.RETURN_VALIDATION_CONFIG: "{summary}",
    Intent.RETURNS_SUBMITTABLE_BY_DEPT: "{summary}",

    Intent.NONXBRL_RETURN_LIST: "{summary}",
    Intent.NONXBRL_RETURN_PROFILE: "{summary}",

    Intent.DEPT_RETURN_ACCESS_MATRIX: "{summary}",
    Intent.MY_RETURN_ACCESS: "{summary}",
    Intent.DEPT_FULL_RETURN_LIST: "{summary}",

    Intent.SUBMISSION_STATUS: "{summary}",
    Intent.SUBMISSION_LIST: "{summary}",
    Intent.SUBMISSION_DETAIL: "{summary}",
    Intent.SUBMISSIONS_FOR_RETURN: "{summary}",
    Intent.MY_SUBMISSION_HISTORY: "{summary}",

    Intent.MENU_LIST: "{summary}",
    Intent.MODULE_DETAIL: "{summary}",
    Intent.MODULE_CHILDREN: "{summary}",

    Intent.AUDIT_HISTORY: "{summary}",
    Intent.AUDIT_ENTITY_TRAIL: "{summary}",
    Intent.SECURITY_EVENTS: "{summary}",
    Intent.LOG_QUERY: "{summary}",

    Intent.USER_ACCESS_SUMMARY: "{summary}",
    Intent.CROSS_ENTITY_QUERY: "{summary}",

    Intent.BANK_INFO: "{summary}",
    Intent.SEGMENT_INFO: "{summary}",
    Intent.NOTIFICATION_QUERY: "{summary}",
}


def render(intent: Intent | str, result: dict) -> str:
    """Render *result* (a handler's QueryResult dict) through the template
    registered for *intent*. Falls back to result["summary"] — which every
    handler always populates — on any missing template or format-key
    error, so this function never raises.

    Every handler's `summary` field is already fact-only plain text
    (built directly from real data, not an LLM) — so even the identity
    "{summary}" templates above satisfy the "no LLM-generated facts"
    requirement; per-intent templates can be swapped for richer
    multi-line formats later without touching handlers or callers.
    """
    if isinstance(intent, str):
        try:
            intent = Intent(intent)
        except ValueError:
            return result.get("summary", "")

    template = TEMPLATES.get(intent, "{summary}")

    ctx = dict(result.get("meta", {}))
    ctx["summary"] = result.get("summary", "")
    ctx["label"] = result.get("label", "")
    ctx["found"] = result.get("found", False)

    # Mask any ciphertext-looking values before they can reach a template's
    # {field} substitution (only relevant to intents whose meta echoes back
    # raw user fields directly — most templates above only use {summary},
    # which handlers already build with plain-language phrasing, not raw
    # attribute dumps).
    for key, value in list(ctx.items()):
        ctx[key] = _display_value(key, value)

    try:
        return template.format(**ctx)
    except (KeyError, IndexError, ValueError):
        return result.get("summary", "")
